import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import LandingLayout from "../layouts/landing.layout";
// import '@/styles/globals.css'

// imported styling here
import {
  HeroSection,
  Wrapper,
  Experience,
  Associates,
  Section,
  OfferContainer,
  Details,
  Tabs,
  SearchForm,
  BannerSection,
} from "../../styles/home.style";
import { Box } from "@mui/material";

// slider
import Marquee from "react-fast-marquee";
import { BiSearch } from "react-icons/bi";
import { BsArrowRight, BsTelephoneFill } from "react-icons/bs";

// brand images are imported here
import {
  brandmovers,
  burtech,
  dcfoods,
  divichotel,
  finlab,
  nigerPolice,
  weather,
} from "../../assets/clients";
import { useState } from "react";

const images = [
  brandmovers,
  burtech,
  dcfoods,
  divichotel,
  finlab,
  nigerPolice,
  weather,
];

/**
 *
 * @description this is the Home page section
 * @returns {React.JSX.Element}
 */
const Home = () => {
  const LogoMarquee = () => {
    return (
      <Marquee gradient={false}>
        {images.map((image, index) => (
          <Box key={index} mr="10px">
            <Image src={image} alt="Logo" width={100} height={50} />
          </Box>
        ))}
      </Marquee>
    );
  };
  const [activeTab, setActiveTab] = useState(0);
  const tabTitles = [
    "Software Development",
    "Testing & QA",
    "Application Services",
    "UX/UI Design",
    "IT Consulting",
    "Data Analytics",
    "Cyber Security",
  ];
  const tabDetails = [
    "A1 software development company with 33 years of business excellence, we can develop reliable, scalable and secure software solutions for any OS, browser and device. We bring together deep industry expertise and the latest IT advancements to deliver custom solutions and products that perfectly fit the needs and behavior of their users.",
    "A2 software development company with 33 years of business excellence, we can develop reliable, scalable and secure software solutions for any OS, browser and device. We bring together deep industry expertise and the latest IT advancements to deliver custom solutions and products that perfectly fit the needs and behavior of their users.",
    "A3 software development company with 33 years of business excellence, we can develop reliable, scalable and secure software solutions for any OS, browser and device. We bring together deep industry expertise and the latest IT advancements to deliver custom solutions and products that perfectly fit the needs and behavior of their users.",
    "A4 software development company with 33 years of business excellence, we can develop reliable, scalable and secure software solutions for any OS, browser and device. We bring together deep industry expertise and the latest IT advancements to deliver custom solutions and products that perfectly fit the needs and behavior of their users.",
    "A5 software development company with 33 years of business excellence, we can develop reliable, scalable and secure software solutions for any OS, browser and device. We bring together deep industry expertise and the latest IT advancements to deliver custom solutions and products that perfectly fit the needs and behavior of their users.",
    "A6 software development company with 33 years of business excellence, we can develop reliable, scalable and secure software solutions for any OS, browser and device. We bring together deep industry expertise and the latest IT advancements to deliver custom solutions and products that perfectly fit the needs and behavior of their users.",
    "A7 software development company with 33 years of business excellence, we can develop reliable, scalable and secure software solutions for any OS, browser and device. We bring together deep industry expertise and the latest IT advancements to deliver custom solutions and products that perfectly fit the needs and behavior of their users.",
  ];

  const handleTabClick = (index) => {
    setActiveTab(index);
  };

  return (
    <>
      <Head>
        <title>Tanta Innovatives Limited</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroSection>
        <Wrapper>
          <p className="headline">Making a Better Reality</p>
          <h1>TRANSFORM YOUR BUSINESS WITH CUTTING-EDGE SOFTWARE SOLUTIONS.</h1>
          <div className="red-line"></div>

          <Experience>
            <div>
              <h1>13+</h1>
              <h4>YEARS EXPERIENCE IN IT CONSULTING</h4>
            </div>
            <div>
              <p className="details">
                We have been providing bespoke and platform-based solutions to
                large, mid-size and small businesses in Healthcare, Banking,
                Retail, Telecom, and other industries for over 13 years.
              </p>
            </div>
          </Experience>

          <Associates>
            <div className="wrapper">
              <div className="carousel">
                <div>
                  <LogoMarquee logos={images} />
                </div>
              </div>
            </div>
          </Associates>
        </Wrapper>
      </HeroSection>

      {/* Offers Section starts here */}
      <Section>
        <Wrapper>
          <OfferContainer>
            <Details>
              <SearchForm>
                <div className="search-box">
                  <BiSearch />
                  <input type="text" placeholder="Search anything here" />
                </div>
              </SearchForm>

              <div className="offer-details">
                <h3>{tabTitles[activeTab]}</h3>
                <div className="red-line_small"></div>
                <p>{tabDetails[activeTab]}</p>
                <Link href="/">
                  learn more <BsArrowRight />
                </Link>
              </div>
            </Details>
            <Tabs>
              <h3>Our Offering</h3>
              <div className="red-line_small"></div>
              <div className="tabs-container">
                <ul>
                  {tabTitles.map((title, index) => (
                    <li
                      key={index}
                      className={activeTab === index ? "active" : ""}
                    >
                      <button onClick={() => handleTabClick(index)}>
                        {title}
                      </button>
                    </li>
                  ))}
                </ul>
              </div>
            </Tabs>
          </OfferContainer>
        </Wrapper>
      </Section>
      <BannerSection>
        {/* <Wrapper> */}
        <div className="banner-details">
          <div>
            <p className="details-title1">INDUSTRIES WE SERVE</p>
            <p className="details-title2">
              For your very specific industry,we have highly-tailored IT
              solutions.
            </p>
            <p className="details-title2"></p>
          </div>
          <div className="cta-wrapper">
            <div className="cta-phone">
              <span>
                <BsTelephoneFill className="phone-icon" />
              </span>
              <p>(01) 123 555 656</p>
            </div>
            <button>Let’s work together</button>
          </div>
        </div>
        {/*</Wrapper> */}
      </BannerSection>
    </>
  );
};

Home.getLayout = (page) => {
  return <LandingLayout>{page}</LandingLayout>;
};
export default Home;

//................//
import Navbar from "./components/Navbar";
import CartContainer from "./components/CartContainer";
import { useDispatch, useSelector } from "react-redux";
import { calculateTotals, getCartItems } from "./features/cart/cartSlice";
import { useEffect } from "react";
import Modal from "./components/Modal";

function App() {
  const { cartItems, isLoading } = useSelector((store) => store.cart);
  const { isOpen } = useSelector((store) => store.modal);
  const dispatch = useDispatch();

  useEffect(() => {
    dispatch(calculateTotals());
  }, [cartItems]);

  useEffect(() => {
    dispatch(getCartItems("random"));
  }, []);

  if (isLoading) {
    return (
      <div className="loading">
        <h1>Loading...</h1>
      </div>
    );
  }

  return (
    <main>
      {isOpen && <Modal />}
      <Navbar />
      <CartContainer />
    </main>
  );
}
export default App;
